### ISSUE TITLE
Internet Explorer 8

### ISSUE THREAD

**Issue by dmeijboom** [cwdx/tabs-to-dropdown#2]
In IE8 the plugin works as expected (hooray!) but some styling does not work (backgroundColor and the linkColor doesn't work).

![schermafbeelding 2014-05-09 om 11 22 40](https://cloud.githubusercontent.com/assets/3341876/2926378/b34e98de-d75b-11e3-85ed-497f52139001.png)

**Comment by cwdx** [comment]
Yes, well that's due to the fact that IE8 doesn't support rgba colors. So a adding a couple of hex colors should fix that problem.
